### ISSUE TITLE
关于如何使用gpu训练的问题

### ISSUE THREAD

**Issue by xinyuyaobianshen** [bubbliiiing/faster-rcnn-keras#17]
是按照博主的环境配置的
![image](https://user-images.githubusercontent.com/66080585/83265356-f94e3b00-a1f3-11ea-9b9d-cf06d2d9e562.png)
（我的其他项目是可以用gpu训练的。）
同时，我也在博主的train.py中加了
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
可是训练的时候使用的还是cpu，无法用gpu加速，训练得太慢了。
![image](https://user-images.githubusercontent.com/66080585/83265200-bf7d3480-a1f3-11ea-901e-4a2d452147d0.png)
可爱的博主知道是什么原因吗？
求指教！

**Comment by xinyuyaobianshen** [comment]
![image](https://user-images.githubusercontent.com/66080585/83267232-7c709080-a1f6-11ea-8341-6f5ab41c03ca.png)
还有还有，你昨天不是更新了frcnn_training.py么，它还是报错啦，你有空的时候再修改一下下好吗？

**Comment by bubbliiiing** [comment]
报了什么错误啊

**Comment by bubbliiiing** [comment]
tensorflow应该是安装了GPU版本的话都是用GPU的吧，你怎么确定是cpu的啊

**Comment by bubbliiiing** [comment]
training我昨天又修改过了

**Comment by xinyuyaobianshen** [comment]
> tensorflow应该是安装了GPU版本的话都是用GPU的吧，你怎么确定是cpu的啊

我的显卡是1080Ti，环境cuda10.0，cudnn7.4.1

第一，我提的问题里那个截图，里面写着cpu的情况，说明在运行train的时候调度的是cpu，如果我运行别可以用gpu加速的项目，运行后，应该显示GPU的情况。

第二，训练时，GPU使用情况如下图：
![image](https://user-images.githubusercontent.com/66080585/83318937-2c341580-a26c-11ea-9ba9-06073ee543bb.png)
我pycharm的gpu使用率只有7Mib，还不如我远程的teamviewer占得多，总GPU使用率只有百分之二十，说明训练的时候根本没用gpu加速。

第三，训练一轮的时间。我这里2000张图，训练一轮要1个小时40分钟，这太慢了吧。如果训练100轮，那得训练好几天啊。对于我显卡的型号，是不太科学的吧……所以时间上来看，也没有用gpu加速。

啊，可爱的博主救救我

**Comment by bubbliiiing** [comment]
你发图我看不见，你可以BILIBILI联系我吧，你这个1080ti确实不应该1小时40分钟

**Comment by xinyuyaobianshen** [comment]
> 你发图我看不见，你可以BILIBILI联系我吧，你这个1080ti确实不应该1小时40分钟

按照博主的方式解决啦！
卸载了tensorflow和tensorflow-gpu以及keras，再重新装了tensorflow-gpu和keras
然后发现我的显卡驱动版本不够，重新更新了显卡驱动。
现在已经可以用gpu训练啦！
感谢
