### ISSUE TITLE
为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？

### ISSUE THREAD

**Issue by chenjjjjuu** [bubbliiiing/faster-rcnn-keras#25]

**Comment by bubbliiiing** [comment]
数据集是怎么样的呀

**Comment by chenjjjjuu** [comment]
就是正常的voc2007数据集啊，我看我没有设置学习率，有没有可能默认学习率为0，参数得不到更新所以准确率一直在45十这样。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Bubbliiiing&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月8日(星期三) 上午10:53
收件人:&nbsp;&quot;bubbliiiing/faster-rcnn-keras&quot;<faster-rcnn-keras@noreply.github.com&gt;;
抄送:&nbsp;&quot;chenjjjjuu&quot;<1540358700@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)

**Comment by bubbliiiing** [comment]
学习率我有设置，你有使用2012+2007吗，应该这样会好一些

**Comment by chenjjjjuu** [comment]
您好，请问你有微信吗？方便加一下吗？

---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年7月8日(周三) 下午5:26
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送: "chenjjjjuu"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)




 
Reopened #25.

**Comment by chenjjjjuu** [comment]
您好，方便加下微信吗？



---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年7月8日(周三) 下午5:26
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送: "chenjjjjuu"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)




 
Reopened #25.

**Comment by chenjjjjuu** [comment]
作者你好，我那原始权重测试准确率五十几，然后又训练了100次还是五十几，什么原因啊



---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年7月8日(周三) 下午5:26
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送: "chenjjjjuu"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)




 
Reopened #25.

**Comment by bubbliiiing** [comment]
每次只传入一张图片，最好在训练的时候平衡一下样本，我之前没有去考虑样本平衡的问题，你可以试试每一次传入包含不同的种类的图片

**Comment by bubbliiiing** [comment]
比如说你voc有20个类，你可以考虑每一个类传入一次图片

**Comment by bubbliiiing** [comment]
比如说你voc有20个类，你可以考虑每一个类传入一次图片，反复循环。
而且建议使用2007+2012训练

**Comment by chenjjjjuu** [comment]
具体就是每次测试的时候重新生成下test.txt文件吗？



---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年7月17日(周五) 中午1:16
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送: "chenjjjjuu"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)




 
每次只传入一张图片，最好在训练的时候平衡一下样本，我之前没有去考虑样本平衡的问题，你可以试试每一次传入包含不同的种类的图片

**Comment by bubbliiiing** [comment]
就是平衡训练集的数据，比如说voc里面的人和车相比于其它的类就多一些，我们可以考虑对每一个类循环，保证每一次取出的图片都会包含不同的类，这样的话可以让神经网络去多训练一下其它的类

**Comment by chenjjjjuu** [comment]
或者我增大测试样本数量？



---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年7月17日(周五) 中午1:16
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送: "chenjjjjuu"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)




 
每次只传入一张图片，最好在训练的时候平衡一下样本，我之前没有去考虑样本平衡的问题，你可以试试每一次传入包含不同的种类的图片

**Comment by bubbliiiing** [comment]
增大测试样本并不影响这个网络训练的不好呀。。。。

**Comment by chenjjjjuu** [comment]
那请问我要怎么样做呢？我只想得出一个好的效果



---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年7月17日(周五) 中午1:33
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送: "chenjjjjuu"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)




 
就是平衡训练集的数据，比如说voc里面的人和车相比于其它的类就多一些，我们可以考虑对每一个类循环，保证每一次取出的图片都会包含不同的类，这样的话可以让神经网络去多训练一下其它的类

**Comment by chenjjjjuu** [comment]
您写的这个代码应该是没有问题的吧？那我用voc2012试一试效果可以好点吗？



---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年7月17日(周五) 中午1:36
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送: "chenjjjjuu"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)




 
增大测试样本并不影响这个网络训练的不好呀。。。。

**Comment by chenjjjjuu** [comment]
您好，可以告诉我该怎样做吗？现在github上也只有您的代码完整好用了。



---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年7月17日(周五) 中午1:36
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送: "chenjjjjuu"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)




 
增大测试样本并不影响这个网络训练的不好呀。。。。

**Comment by bubbliiiing** [comment]
你可以参考这个来

**Comment by bubbliiiing** [comment]
#---------------------------------------------------#
#   训练数据生成器
#---------------------------------------------------#
def data_generator(annotation_lines, batch_size, input_shape, anchors, num_classes):
    '''data generator for fit_generator'''
    all_classes = []
    for i in range(num_classes):
        new_classes = []
        for annotation_line in annotation_lines:
            flag = False
            line = annotation_line.split()
            boxes = np.array([np.array(list(map(int,box.split(',')))) for box in line[1:]])
            for box in boxes:
                if box[-1]==i:
                    flag = True
            if flag == True:
                new_classes.append(annotation_line)
        all_classes.append(new_classes)

    count_num = list(np.zeros(num_classes))

    i = 0
    while True:
        image_data = []
        box_data = []
        for b in range(batch_size):
            if count_num[i] == 0:
                random.shuffle(all_classes[i])
            image, box = get_random_data(all_classes[i][int(count_num[i])], input_shape, random=True)
            image_data.append(image)
            box_data.append(box)
            count_num[i] = (count_num[i]+1) % len(all_classes[i])
            i=(i+1)%num_classes

        image_data = np.array(image_data)
        box_data = np.array(box_data)
        y_true = preprocess_true_boxes(box_data, input_shape, anchors, num_classes)
        yield [image_data, *y_true], np.zeros(batch_size)
这个是我写在yolo里面的代码，你可以看看这个思路，就是让每一个类进行循环。

**Comment by bubbliiiing** [comment]
`def data_generator(annotation_lines, batch_size, input_shape, anchors, num_classes):
    '''data generator for fit_generator'''
    all_classes = []
    for i in range(num_classes):
        new_classes = []
        for annotation_line in annotation_lines:
            flag = False
            line = annotation_line.split()
            boxes = np.array([np.array(list(map(int,box.split(',')))) for box in line[1:]])
            for box in boxes:
                if box[-1]==i:
                    flag = True
            if flag == True:
                new_classes.append(annotation_line)
        all_classes.append(new_classes)

    count_num = list(np.zeros(num_classes))

    i = 0
    while True:
        image_data = []
        box_data = []
        for b in range(batch_size):
            if count_num[i] == 0:
                random.shuffle(all_classes[i])
            image, box = get_random_data(all_classes[i][int(count_num[i])], input_shape, random=True)
            image_data.append(image)
            box_data.append(box)
            count_num[i] = (count_num[i]+1) % len(all_classes[i])
            i=(i+1)%num_classes

        image_data = np.array(image_data)
        box_data = np.array(box_data)
        y_true = preprocess_true_boxes(box_data, input_shape, anchors, num_classes)
        yield [image_data, *y_true], np.zeros(batch_size)`
你可以按照这个来，这个是我写在yolo里的

**Comment by bubbliiiing** [comment]
`
def data_generator(annotation_lines, batch_size, input_shape, anchors, num_classes):
    '''data generator for fit_generator'''
    all_classes = []
    for i in range(num_classes):
        new_classes = []
        for annotation_line in annotation_lines:
            flag = False
            line = annotation_line.split()
            boxes = np.array([np.array(list(map(int,box.split(',')))) for box in line[1:]])
            for box in boxes:
                if box[-1]==i:
                    flag = True
            if flag == True:
                new_classes.append(annotation_line)
        all_classes.append(new_classes)

    count_num = list(np.zeros(num_classes))

    i = 0
    while True:
        image_data = []
        box_data = []
        for b in range(batch_size):
            if count_num[i] == 0:
                random.shuffle(all_classes[i])
            image, box = get_random_data(all_classes[i][int(count_num[i])], input_shape, random=True)
            image_data.append(image)
            box_data.append(box)
            count_num[i] = (count_num[i]+1) % len(all_classes[i])
            i=(i+1)%num_classes

        image_data = np.array(image_data)
        box_data = np.array(box_data)
        y_true = preprocess_true_boxes(box_data, input_shape, anchors, num_classes)
        yield [image_data, *y_true], np.zeros(batch_size)
`

**Comment by chenjjjjuu** [comment]
嗯嗯，然后请问一下您这个是训练了多少个epoch 的预训练模型加载进去的？谢谢您百忙之中抽空回答我问题

---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年7月20日(周一) 上午9:31
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送: "chenjjjjuu"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)




 
#---------------------------------------------------#
 
训练数据生成器
 
#---------------------------------------------------#
 def data_generator(annotation_lines, batch_size, input_shape, anchors, num_classes):
 '''data generator for fit_generator'''
 all_classes = []
 for i in range(num_classes):
 new_classes = []
 for annotation_line in annotation_lines:
 flag = False
 line = annotation_line.split()
 boxes = np.array([np.array(list(map(int,box.split(',')))) for box in line[1:]])
 for box in boxes:
 if box[-1]==i:
 flag = True
 if flag == True:
 new_classes.append(annotation_line)
 all_classes.append(new_classes)
 count_num = list(np.zeros(num_classes)) i = 0 while True:     image_data = []     box_data = []     for b in range(batch_size):         if count_num[i] == 0:             random.shuffle(all_classes[i])         image, box = get_random_data(all_classes[i][int(count_num[i])], input_shape, random=True)         image_data.append(image)         box_data.append(box)         count_num[i] = (count_num[i]+1) % len(all_classes[i])         i=(i+1)%num_classes     image_data = np.array(image_data)     box_data = np.array(box_data)     y_true = preprocess_true_boxes(box_data, input_shape, anchors, num_classes)     yield [image_data, *y_true], np.zeros(batch_size)  
这个是我写在yolo里面的代码，你可以看看这个思路，就是让每一个类进行循环。

**Comment by bubbliiiing** [comment]
哪个呀

**Comment by chenjjjjuu** [comment]
您好，就是faster rcnn里面的那个voc_weights.h5文件，请问这个文件是训练了多少次得到的权重？



---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年7月21日(周二) 上午10:54
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送: "chenjjjjuu"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)




 
哪个呀

**Comment by chenjjjjuu** [comment]
作者您好，本人编程能力有限，能不能帮我把这部分完善一下？价格私聊

---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年7月20日(周一) 上午9:32
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送: "chenjjjjuu"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)




 
`def data_generator(annotation_lines, batch_size, input_shape, anchors, num_classes):
 '''data generator for fit_generator'''
 all_classes = []
 for i in range(num_classes):
 new_classes = []
 for annotation_line in annotation_lines:
 flag = False
 line = annotation_line.split()
 boxes = np.array([np.array(list(map(int,box.split(',')))) for box in line[1:]])
 for box in boxes:
 if box[-1]==i:
 flag = True
 if flag == True:
 new_classes.append(annotation_line)
 all_classes.append(new_classes)
 count_num = list(np.zeros(num_classes)) i = 0 while True:     image_data = []     box_data = []     for b in range(batch_size):         if count_num[i] == 0:             random.shuffle(all_classes[i])         image, box = get_random_data(all_classes[i][int(count_num[i])], input_shape, random=True)         image_data.append(image)         box_data.append(box)         count_num[i] = (count_num[i]+1) % len(all_classes[i])         i=(i+1)%num_classes     image_data = np.array(image_data)     box_data = np.array(box_data)     y_true = preprocess_true_boxes(box_data, input_shape, anchors, num_classes)     yield [image_data, *y_true], np.zeros(batch_size)`  
你可以按照这个来，这个是我写在yolo里的

**Comment by chenjjjjuu** [comment]
作者您好，最近经常给您发的邮件，只能怪您代码写的我感觉是最好用的，哈哈。
请问下面两个文件中，每个路径所指的权重作用不一样吗？我应该修改哪一个？谢谢作者，麻烦您有时间回复一下

---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年7月17日(周五) 中午1:33
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送: "chenjjjjuu"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)




 
就是平衡训练集的数据，比如说voc里面的人和车相比于其它的类就多一些，我们可以考虑对每一个类循环，保证每一次取出的图片都会包含不同的类，这样的话可以让神经网络去多训练一下其它的类

**Comment by bubbliiiing** [comment]
我就大概训练了20个世代，太慢了训练起来

**Comment by bubbliiiing** [comment]
你是不知道去修改那一部分吗？frcnn training

**Comment by chenjjjjuu** [comment]
谢谢您的回复 是的



---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年8月6日(周四) 上午10:18
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送: "chenjjjjuu"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)




 
你是不知道去修改那一部分吗？frcnn training

**Comment by chenjjjjuu** [comment]
作者您好，针对这个问题您可以有时间帮我改一下吗？本人能力有限。谢谢老师



---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年7月20日(周一) 上午9:31
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送: "chenjjjjuu"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)




 
你可以参考这个来

**Comment by bubbliiiing** [comment]
我重新训练看看

**Comment by chenjjjjuu** [comment]
好，谢谢你啊 我等你



---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年8月7日(周五) 下午3:17
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送: "chenjjjjuu"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)




 
我重新训练看看

**Comment by bubbliiiing** [comment]
训练了两天，07+12 map71.74%

**Comment by bubbliiiing** [comment]
我再简单整理一下，再上传

**Comment by chenjjjjuu** [comment]
嗯嗯 谢谢您 上传好还麻烦您通知一下我


 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bubbliiiing"<notifications@github.com&gt;; 
发送时间: 2020年8月10日(星期一) 上午10:41
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;; 
抄送: "粉粉-安徽"<1540358700@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)





 
我再简单整理一下，再上传

**Comment by chenjjjjuu** [comment]
还是以前的代码吗？
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bubbliiiing"<notifications@github.com&gt;; 
发送时间: 2020年8月10日(星期一) 上午10:41
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;; 
抄送: "粉粉-安徽"<1540358700@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)





 
训练了两天，07+12 map71.74%

**Comment by bubbliiiing** [comment]
已经上传了，权重也上传了，重新下载吧

**Comment by chenjjjjuu** [comment]
好 谢谢你 我先试试看


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bubbliiiing/faster-rcnn-keras"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月11日(星期二) 中午11:35
收件人:&nbsp;"bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送:&nbsp;"粉粉-安徽"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)





 
Closed #25.

**Comment by chenjjjjuu** [comment]
作者您好，已重新训练自己的数据集，定位效果不错，但是分类效果太差，不如ssd，训练loss不再下降就好了吗？如何改进呢？



---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年8月11日(周二) 中午11:35
收件人: "bubbliiiing/faster-rcnn-keras"<faster-rcnn-keras@noreply.github.com&gt;;
抄送: "chenjjjjuu"<1540358700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bubbliiiing/faster-rcnn-keras] 为什么我训练了120个epoch了，准确率也只有58，上不去，voc2007数据集。请问你们的超参数是多少？ (#25)




 
已经上传了，权重也上传了，重新下载吧

**Comment by bubbliiiing** [comment]
FRCNN本来07+12的效果就不如ssd…，修改意见我也不知道如何是好
