### ISSUE TITLE
关于Get_map.py文件运行中的报错

### ISSUE THREAD

**Issue by cir9no** [bubbliiiing/faster-rcnn-keras#31]
Traceback (most recent call last):
  File "f:/dece/faster-rcnn-keras-master/get_map.py", line 706, in <module>
    + " ; Recall=" + "{0:.2f}%".format(rec[score05_idx]*100) + " ; Precision=" + "{0:.2f}%".format(prec[score05_idx]*100))                                                                                          ore05_idx]*100))
IndexError: index 0 is out of bounds for axis 0 with size 0

报错显示如上

**Comment by bubbliiiing** [comment]
你是不是在B站有联系我啊

**Comment by cir9no** [comment]
> 你是不是在B站有联系我啊
没有。。。

**Comment by bubbliiiing** [comment]
xml是不是有无关的类啊

**Comment by cir9no** [comment]
恩， 复查xml发现是录入时录入无关类导致的问题。thx!
