### ISSUE TITLE
模型是你训练的吗？

### ISSUE THREAD

**Issue by busyyang** [bubbliiiing/faster-rcnn-keras#8]
这个模型是你自己训练的还是下载的论文原作者的？感觉去检测视频时候，效果很差。

**Comment by bubbliiiing** [comment]
可能训练不够充分，可能可以重新训练一下

**Comment by busyyang** [comment]
我后面自己有接着训练了一下，loss下降了不少，但是 感觉效果还是一般，而且速度也很慢，比起YOLO来说，速度差多了。

**Comment by busyyang** [comment]
我把这个关了。
